import type { ModuleType } from "../api/client";

const MODULE_ALIASES: Record<string, ModuleType | string> = {
  manuscript: "manuscript",
  manuscripts: "manuscript",
  chapter: "manuscript",
  chapters: "manuscript",
  scene: "manuscript",
  scenes: "manuscript",
  character: "character",
  characters: "character",
  encyclopedia: "encyclopedia",
  article: "encyclopedia",
  articles: "encyclopedia",
  relationship: "relationship",
  relationships: "relationship",
  location: "location",
  locations: "location",
  place: "location",
  places: "location",
  systems: "systems",
  system: "systems",
  magic: "systems",
  tech: "systems",
  technology: "systems",
  maps: "maps",
  map: "maps",
  timeline: "timeline",
  timelines: "timeline",
  event: "timeline",
  events: "timeline",
  species: "species",
  races: "species",
  race: "species",
  cultures: "cultures",
  culture: "cultures",
  items: "items",
  item: "items",
  objects: "items",
  object: "items",
  arcs: "arcs",
  arc: "arcs",
  plots: "arcs",
  plot: "arcs",
  languages: "languages",
  language: "languages",
  religions: "religions",
  religion: "religions",
  beliefs: "religions",
  belief: "religions",
  research: "research",
  notes: "research",
  philosophies: "philosophies",
  philosophy: "philosophies",
  calendar: "calendar",
  calendars: "calendar",
};

export function mapModuleName(name: string): string | null {
  return MODULE_ALIASES[name.trim().toLowerCase()] || null;
}
