[package]
name = "tavern-db"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
argon2 = { workspace = true }
chrono = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
sqlx = { workspace = true }
tavern-core = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
hex = { workspace = true }
