/** Short hover tips for self-guided UI discovery. */
export const TIPS = {
  brand: "Return to your project list",
  focus: "Collapse Modules, Items, and Inspector — tap again to restore",
  chromeModules: "Show or hide the module rail (Manuscript, Characters, …)",
  chromeList: "Show or hide the item list for the current module",
  chromeInspector: "Show or hide the inspector (delete, sharing, bible)",
  chromeTools: "Show or hide export, backup, and account actions",
  collapsePanel: "Hide this panel — reopen from the top bar toggles",
  exportMd: "Download the manuscript as Markdown",
  exportDocx: "Download the manuscript as DOCX (needs pandoc on the server)",
  backup: "Download a full .tavern project backup zip",
  logout: "End this session",
  moduleManuscript: "Chapters and scenes — TipTap editor, corkboard, word goals",
  moduleCharacter: "People and creatures — panel canvases for bios and traits",
  moduleEncyclopedia: "Flexible lore articles, items, and research notes",
  moduleRelationship: "Graph of character links — drag between nodes to connect",
  moduleLocation: "Places and settings — details, prose, and reference images",
  moduleSystems: "Magic or tech rules — attributes, stats, and example tables",
  moduleMaps: "Upload a chart and pin locations on it",
  moduleTimeline: "Chronological events sorted by date",
  moduleSpecies: "Peoples and creatures as species entries — traits and ranges",
  moduleCultures: "Societies, customs, and values tied to places and languages",
  moduleItems: "Objects, artifacts, and gear — details, prose, and images",
  moduleArcs: "Plot or character arcs — summary, beats, and linked cast",
  moduleLanguages: "Conlangs and dialects — lexicon tables and notes",
  moduleReligions: "Faiths and belief systems — rites, symbols, and links",
  moduleResearch: "Working notes and open questions — findings, sources, related lore",
  modulePhilosophies: "Schools of thought — tenets, thinkers, and influence",
  moduleCalendar: "World calendars — months, eras, holidays, and epoch notes",
  newElement: "Create a new item in the current module",
  corkboard: "Manuscript chapters on a grid — drag onto another card to reorder",
  corkDrag: "Drag onto another card’s slot to change chapter order",
  corkRename: "Rename this chapter — saves when you leave the field",
  corkOpen: "Open this chapter in the manuscript editor",
  corkUndo: "Undo the last corkboard reorder or rename",
  corkRedo: "Redo a corkboard change you undid",
  corkReset: "Restore chapter order to how it was when you opened Corkboard",
  addPanel: "Add another panel type to this page",
  addPage: "Add another page/tab of panels on this element",
  pageSelect: "Switch between pages of panels on this element",
  elementTitle: "Rename this item — saves when you leave the field",
  panelTitle: "Rename this panel",
  panelDrag: "Drag to move this panel on the canvas",
  deletePanel: "Remove this panel from the page",
  addAttrRow: "Add a key/value row to this panel",
  addListItem: "Add another list item",
  addTableRow: "Add a blank row to the table",
  panelText: "Markdown text for this panel — saves on blur",
  panelLinks: "One linked element id per line",
  imageCaption: "Optional caption under this image",
  removeImage: "Remove this image from the panel",
  msTitle: "Chapter or scene title — saves on blur",
  msSource: "Toggle between rich editor and raw markdown source",
  msGoal: "Optional word-count goal for this document",
  msWords: "Live word count of the current draft",
  msSave: "Save manuscript text and word goal to the server",
  msEditor: "Write prose here. Use [[Module:Title]] for wiki links",
  msQuickLink: "Insert a wiki-link token for this worldbuilding item",
  graphHint: "Drag from one node handle to another to create a relationship",
  undoLink: "Delete the most recently created link on this graph",
  inspector: "Selected item details, sharing, and export helpers",
  grant: "If that username exists they get access — no confirmation either way",
  inviteLink: "Single-use link, expires in 7 days. Share out of band.",
  grantRole: "Editors can write; viewers can only read",
  leaveProject: "Remove your own access to this shared project",
  accounts: "Create writer accounts for this instance",
  createUser: "Add a login for another writer on this server",
  createUserPass: "At least 12 characters — not the word admin",
  createUserAdmin: "Admins can create accounts but cannot open others’ unshared projects",
  deleteElement: "Permanently remove this element",
  wikiTip: "In manuscript text, link with [[Character:Name]] or similar",
  bible: "Export worldbuilding notes as a Markdown bible",
  createProject: "Start a blank project",
  importProject: "Import Campfire HTML export, .tavern backup, or intermediate JSON",
  tutorial: "Load a guided sample covering every module — safe to delete later",
  openProject: "Open this project workspace",
  deleteProject: "Permanently delete this project and its data",
  loginUser: "Account username",
  loginPass: "Account password",
  mapUpload: "Set or replace the background image for this map",
  mapPin: "Click the map to place a pin; select a pin to rename or link a location",
  mapPinLabel: "Display name for the selected pin",
  mapPinLink: "Optionally link this pin to a Location element",
  mapPinRemove: "Delete the selected pin from the map",
  timelineDate: "Sortable date string (ISO-like) used to order events",
  timelineLabel: "Human-readable label shown on the timeline rail",
  timelineEvent: "Select this event to edit its panels and date",
  uploadImage: "Upload an image into this project's asset library",
  addImageUrl: "Attach an external image URL to this panel",
} as const;

export type TipKey = keyof typeof TIPS;
